name: PHPStan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

permissions:
  contents: read
  issues: write

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer

      - name: Install deps
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Debug workspace and paths
        run: |
          echo "Obecny katalog roboczy:"
          pwd
          echo "--- Zawartość katalogu głównego ---"
          ls -la
          echo "--- Szukam composer.json ---"
          find . -maxdepth 2 -name composer.json -print
          echo "--- Szukam katalogów kodu ---"
          ls -la src || echo "Brak katalogu src"
          ls -la app || echo "Brak katalogu app"

      - name: Run PHPStan
        id: stan
        continue-on-error: true
        shell: bash
        run: |
          echo "Uruchamiam PHPStan na katalogu: src"
          ./vendor/bin/phpstan analyse --no-progress --memory-limit=1G src \
            | tee phpstan-report.txt
          echo "exitcode=${PIPESTATUS[0]}" >> "$GITHUB_OUTPUT"

      - name: Upload PHPStan report (artifact)
        if: steps.stan.outputs.exitcode != '0'
        uses: actions/upload-artifact@v4
        with:
          name: phpstan-report
          path: phpstan-report.txt

      - name: Create Issue on PHPStan failure
        if: steps.stan.outputs.exitcode != '0'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          head -n 80 phpstan-report.txt > phpstan-issue-snippet.txt
          {
            echo "Commit: ${{ github.sha }}";
            echo;
            echo "Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}";
            echo;
            echo "Errors (first lines):";
            echo '```';
            cat phpstan-issue-snippet.txt;
            echo '```';
            echo;
            echo "Full report is attached as an artifact.";
          } > issue_body.txt
          gh issue create \
            --title "PHPStan errors in commit ${{ github.sha }}" \
            --body-file issue_body.txt \
            --label "phpstan-error"

      - name: Fail job if PHPStan failed
        if: steps.stan.outputs.exitcode != '0'
        run: exit 1
