name: PHPStan (main push -> create issue on fail)

on:
  push:
    branches: ['main']

permissions:
  contents: read
  issues: write

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer

      - name: Install deps
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Debug workspace and paths
        run: |
          echo "pwd: $(pwd)"
          ls -la
          echo "--- find composer.json ---"
          find . -maxdepth 2 -name composer.json -print
          echo "--- ls src / app ---"
          ls -la src || echo "Brak katalogu src"
          ls -la app || echo "Brak katalogu app"

      - name: Run PHPStan
        id: stan
        shell: bash
        continue-on-error: true
        run: |
          echo "Uruchamiam PHPStan na katalogu: src"
          ./vendor/bin/phpstan analyse --no-progress --memory-limit=1G src | tee phpstan-report.txt
          code=${PIPESTATUS[0]}
          echo "Exit code was: $code"
          echo "exitcode=$code" >> $GITHUB_OUTPUT

      - name: Debug exitcode
        run: echo "PHPStan exitcode=${{ steps.stan.outputs.exitcode }}"

      - name: Upload PHPStan report (artifact)
        if: steps.stan.outputs.exitcode != '0'
        uses: actions/upload-artifact@v4
        with:
          name: phpstan-report
          path: phpstan-report.txt

      - name: Create Issue on PHPStan failure
        if: steps.stan.outputs.exitcode != '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "== gh auth status =="
          gh auth status || true

          head -n 80 phpstan-report.txt > phpstan-issue-snippet.txt
          {
            echo "Commit: ${{ github.sha }}";
            echo;
            echo "Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}";
            echo;
            echo "Errors (first lines):";
            echo '```';
            cat phpstan-issue-snippet.txt;
            echo '```';
            echo;
            echo "Full report is attached as an artifact.";
          } > issue_body.txt

          gh issue create \
            --title "PHPStan errors in commit ${{ github.sha }}" \
            --body-file issue_body.txt \
            --label "phpstan-error"

      - name: Fail job if PHPStan failed
        if: steps.stan.outputs.exitcode != '0'
        run: exit 1
