name: PHPStan (every 15min or manual, blame, dedupe issues, single truncated body)

on:
  schedule:
    - cron: '55 6 * * *'
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # pełna historia dla git blame

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer

      - name: Install deps
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Run PHPStan (JSON output)
        id: stan
        shell: bash
        continue-on-error: true
        run: |
          set +e
          ./vendor/bin/phpstan analyse --no-progress --memory-limit=1G --error-format=json src | tee phpstan-report.json
          code=${PIPESTATUS[0]}
          echo "exitcode=$code" >> "$GITHUB_OUTPUT"
          set -e

      - name: Build annotated report with git blame (inline, single/truncated)
        if: steps.stan.outputs.exitcode != '0'
        env:
          WORKROOT: ${{ github.workspace }}
        run: |
          if ! command -v jq >/dev/null 2>&1; then
            echo "jq not found"; exit 1
          fi

          # Wyciągnij płaską listę (plik, linia, wiadomość)
          jq -r '
            .files
            | to_entries[]
            | .key as $file
            | (.value.messages // [])
            | .[]
            | [$file, (.line // 0), (.message // "")]
            | @tsv
          ' phpstan-report.json > phpstan-flat.tsv || true

          : > phpstan-annotated.txt
          if [ -s phpstan-flat.tsv ]; then
            while IFS=$'\t' read -r file line msg; do
              # Ścieżki względne dla czytelności
              relfile="${file#${WORKROOT}/}"
              relfile="${relfile#./}"
              [ -z "$relfile" ] && relfile="$file"
              # Jeśli plik względny nie istnieje, spróbuj oryginalnej ścieżki
              [ ! -f "$relfile" ] && [ -f "$file" ] && relfile="$file"

              if [ "$line" -gt 0 ] 2>/dev/null; then
                blame=$(git blame -L ${line},${line} --porcelain -- "$relfile" 2>/dev/null || true)
                author=$(echo "$blame" | awk '/^author /{sub(/^author /,""); print; exit}')
                commitsha=$(echo "$blame" | awk '/^commit /{print $2; exit}')
                # Temat commita przez git show (bardziej niezawodne niż "summary")
                summary=""
                if [ -n "$commitsha" ]; then
                  summary=$(git show -s --format=%s "$commitsha" 2>/dev/null || true)
                fi
                [ -z "$author" ] && author="(nieznany autor)"
                [ -z "$commitsha" ] && commitsha="(brak SHA)"
                [ -z "$summary" ] && summary="(no subject)"
                echo "${relfile}:${line} [${author}] ${msg}  -- ${summary} (${commitsha})" >> phpstan-annotated.txt
              else
                echo "${relfile}:${line} [brak dokładnej linii] ${msg}" >> phpstan-annotated.txt
              fi
            done < phpstan-flat.tsv
          else
            echo "Brak szczegółowych wiadomości w phpstan-report.json; poniżej nagłówek JSON:" >> phpstan-annotated.txt
            head -n 200 phpstan-report.json >> phpstan-annotated.txt
          fi

          # Krótkie intro do treści (link do runa + nagłówek)
          {
            echo "Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}";
            echo;
            echo "Errors (annotated):"
            echo
          } > header.txt

          # Zbuduj JEDEN tekst do wstawienia (issue body lub pojedynczy komentarz), ucinany jeśli za duży
          # Limit bezpieczny ~55k bajtów
          MAX=55000
          # Ile bajtów zajmie header + code fences + info o ucięciu
          OVERHEAD=1000
          PAYLOAD=$((MAX - OVERHEAD))
          total=$(wc -c < phpstan-annotated.txt | tr -d ' ')

          : > final_body.txt
          cat header.txt >> final_body.txt
          echo '```' >> final_body.txt
          if [ "$total" -le "$PAYLOAD" ]; then
            cat phpstan-annotated.txt >> final_body.txt
            echo '```' >> final_body.txt
          else
            head -c $PAYLOAD phpstan-annotated.txt >> final_body.txt
            echo >> final_body.txt
            echo '... [TRUNCATED] (report shortened to fit issue/comment size limit)' >> final_body.txt
            echo '```' >> final_body.txt
          fi

      - name: Check for existing open PHPStan issue
        if: steps.stan.outputs.exitcode != '0'
        id: dup
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          count=$(gh issue list --state open --label "phpstan-error" --limit 100 --json number --jq 'length')
          echo "open_count=$count" >> "$GITHUB_OUTPUT"

      - name: Create new issue with single truncated body
        if: steps.stan.outputs.exitcode != '0' && steps.dup.outputs.open_count == '0'
        id: create_issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          num=$(gh issue create \
            --title "PHPStan errors (scheduled/manual run)" \
            --label "phpstan-error" \
            --body-file final_body.txt \
            --json number --jq .number)
          echo "issue_number=$num" >> "$GITHUB_OUTPUT"

      - name: Comment once (single truncated body) on existing issue
        if: steps.stan.outputs.exitcode != '0' && steps.dup.outputs.open_count != '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          num=$(gh issue list --state open --label "phpstan-error" --limit 1 --json number --jq '.[0].number')
          gh issue comment "$num" --body-file final_body.txt

      - name: Close open PHPStan issues (if any)
        if: steps.stan.outputs.exitcode == '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          nums=$(gh issue list --state open --label "phpstan-error" --limit 100 --json number --jq '.[].number')
          if [ -n "$nums" ]; then
            for n in $nums; do
              echo "Zamykam issue #$n (PHPStan green)"
              gh issue close "$n" -c "PHPStan green on workflow run ${{ github.run_id }}"
            done
          else
            echo "Brak otwartych issue do zamknięcia."
          fi

      - name: Fail job if PHPStan failed
        if: steps.stan.outputs.exitcode != '0'
        run: exit 1
