name: PHPStan

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none
          tools: composer

      - name: Install deps
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Debug workspace and paths
        run: |
          echo "Obecny katalog roboczy:"
          pwd
          echo "--- Zawartość katalogu głównego ---"
          ls -la
          echo "--- Szukam composer.json ---"
          find . -maxdepth 2 -name composer.json -print
          echo "--- Szukam katalogów kodu ---"
          ls -la src || echo "Brak katalogu src"
          ls -la app || echo "Brak katalogu app"

      - name: Run PHPStan
        run: |
          echo "Uruchamiam PHPStan na katalogu: src"
          ./vendor/bin/phpstan analyse --no-progress --memory-limit=1G src
